# Generated by Django 4.1.13 on 2024-05-05 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0004_alter_user_login_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientDocument",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="documents/")),
                ("file_content", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("last_updated_file", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
